# code from https://ai.google.dev/gemini-api/docs/quickstart?lang=python

# to do: add a file to install this dependency "pip install -q -U google-generativeai"

# I keep getting 
# WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
# E0000 00:00:1738090470.773087   34308 init.cc:232] grpc_wait_for_shutdown_with_timeout() timed out.
#
#
# these are annoying terminal warnings which are generated by the underlying libraries (gRPC and Abseil) of Gemini while initializing logging configurations. To suppress them
#  "pip install grpcio==1.67.1 grpcio-status==1.67.1 "

import os
import google.generativeai as genai
from cmdCall import cmdCall
from prompt import prompts
from dotenv import load_dotenv
load_dotenv()
# Hardcoded API Key

def gemini(prompt, responseType="Default"):

    #Load API keys from enironment variables
    apiKey = os.getenv("GEMINI_API_KEY")
    #Error message if api is not found
    if apiKey is None:
        raise ValueError("OpenAI API key is not set in environment variables.")

    # Configure Gemini API
    genai.configure(api_key = apiKey)

    try:
        # Create model with safe system_instruction
        model = genai.GenerativeModel(
            model_name="gemini-2.0-flash",
            system_instruction=prompts[responseType]
        )
        response = model.generate_content(prompt)

        # Ensure response.text exists
        return response.text.strip() if response.text else "Error: No response from Gemini."
    
    except Exception as e:
        return f"Error calling Gemini: {e}"

if __name__ == "__main__":
    print(cmdCall(gemini))