# code from https://ai.google.dev/gemini-api/docs/quickstart?lang=python

# to do: add a file to install this dependency "pip install -q -U google-generativeai"

# I keep getting 
# WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
# E0000 00:00:1738090470.773087   34308 init.cc:232] grpc_wait_for_shutdown_with_timeout() timed out.
#
#
# these are annoying terminal warnings which are generated by the underlying libraries (gRPC and Abseil) of Gemini while initializing logging configurations. To suppress them
#  "pip install grpcio==1.67.1 grpcio-status==1.67.1 "


import google.generativeai as genai

def gemini(prompt,responseType="Give a normal response"):
    genai.configure(api_key="AIzaSyD5hnOznfop7WzlHRoUiNBnltayVFL8kbw")
    model = genai.GenerativeModel(
        model_name="gemini-2.0-flash",
        system_instruction=responseType)
    response = model.generate_content(prompt)
    return response.text[:-1] # this return the response from gemini and [:-1] is used to not include the new line character